tcp:
  port: 10001
boss:
  thread:
    count: 2
server:
  port: 8888
worker:
  thread:
    count: 2
so:
  keepalive:  true
  backlog: 100
http:
  maxTotal: 100
  defaultMaxPerRoute: 20
  connectTimeout: 1000
  connectionRequestTimeout: 500
  socketTimeout: 10000
  staleConnectionCheckEnabled: true
spring:
  datasource:
    url: jdbc:mysql://39.108.110.121:3306/smgs?characterEncoding=utf-8
    username: root
    password: qg2018qg
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0