tcp:
  port: 10000
boss:
  thread:
    count: 2
server:
  port: 8888
worker:
  thread:
    count: 2
so:
  keepalive:  true
  backlog: 100
http:
  maxTotal: 100
  defaultMaxPerRoute: 20
  connectTimeout: 1000
  connectionRequestTimeout: 500
  socketTimeout: 10000
  staleConnectionCheckEnabled: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smgs
    username: root
    password: 112316
    driver-class-name: com.mysql.jdbc.Driver